apiVersion: apps/v1
kind: Deployment
metadata:
  name: demp-rpc
  namespace: default
  labels:
    app: demp-rpc
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: demp-rpc
  template:
    metadata:
      labels:
        app: demp-rpc
    spec:
      containers:
        - name: demp-rpc
          image: registry.cn-hangzhou.aliyuncs.com/longfei_deploy/test:0.5
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---
apiVersion: v1
kind: Service
metadata:
  name: demp-rpc-svc
  namespace: default
spec:
  ports:
    - port: 8080
  selector:
    app: demp-rpc
